### ISSUE TITLE
wait_for_command: split multiline entries 

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#55]
Right now dock does this to multiline entries:
```
line = line.replace("\r\n", " ").replace("\n", " ").strip()
```
I think it would be much better to log each line separately, because in case of yum, some logs look pretty chaotic.

**Comment by jpopelka** [comment]
Looks like this has already been fixed with 26ee2b8.

**Comment by TomasTomecek** [comment]
You are right, thanks for catching it!

On the other hand, am still seeing some weird behavior:
```
2015-04-16T12:15:04.738086229Z 2015-04-16 08:15:04,738 - dock.util - DEBUG - <some yum output>
2015-04-16T12:15:04.738086229Z  logrotate
2015-04-16T12:15:04.738086229Z           x86_64 3.8.6-4.el7   repo  63 k
2015-04-16T12:15:04.738086229Z 
2015-04-16T12:15:04.738086229Z Transaction Summary
2015-04-16T12:15:04.738086229Z ==========================
```

But it's not big deal.
